name: Archlinux

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      
    strategy:
      fail-fast: false
      matrix:
        version:
          - gcc-default-x86_64
          - gcc-10-x86_64
          - gcc-9-x86_64
          - gcc-8-x86_64
          - gcc-7-x86_64
          - gcc-6-x86_64
          - gcc-5-x86_64
          - gcc-4.9-x86_64
          - gcc-4.8-x86_64
          - gcc-4.7-x86_64
          - gcc-4.6-x86_64
          - gcc-4.5-x86_64
          - gcc-4.4-x86_64
          - gcc-4.3-x86_64
          - clang-default-x86_64
          - clang-12-x86_64
          - clang-9-x86_64
          - clang-8-x86_64
          - clang-7-x86_64
          - clang-5-x86_64
          - clang-4-x86_64
          - clang-3.5-x86_64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v1.14.1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3.7.0
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}-archlinux-${{ matrix.version }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.10.0
        with:
          context: .
          push: false
          file: ./archlinux/${{ matrix.version }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
